### PR TITLE
Add SchemaRegistry and CloudMetadata APIs

### PR DESCRIPTION
**Pull request by Mongey**

### CODE REVIEW

**Comment by placydo** [comment]
Hey! Any updates on this one?

**Comment by cgroschupp** [comment]
@placydo this PR is in draft status. @Mongey is this PR ready?

**Comment by rjudin** [comment]
@Mongey could we please back on this? Eager to see schema-registry API at https://github.com/Mongey/terraform-provider-confluentcloud/issues/16

**Comment by dmicic** [comment]
Ah, haven't seen this one. Created a duplicate PR: [https://github.com/cgroschupp/go-client-confluent-cloud/pull/11](https://github.com/cgroschupp/go-client-confluent-cloud/pull/11)  😅 Would need this in your [https://github.com/Mongey/terraform-provider-confluentcloud](https://github.com/Mongey/terraform-provider-confluentcloud) 🚀

**Pull request closed without merging**
